# Generated by Django 3.1.2 on 2020-10-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailscout_app', '0004_auto_20201015_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bacteria',
            field=models.CharField(choices=[('acinetobacter baumannii', 'Bacteria_1'), ('B2', 'Bacteria_2'), ('B2', 'Bacteria_3')], max_length=256),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('S1', 'Step_1'), ('S2', 'Step_2'), ('S3', 'Step_3')], default='S1', max_length=2, null=True),
        ),
    ]
