# Generated by Django 3.1.2 on 2020-10-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailscout_app', '0005_auto_20201015_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bacteria',
            field=models.CharField(choices=[('acinetobacter baumannii', 'Bacteria_1'), ('klebsiella pnuemoniae', 'Bacteria_2'), ('escherichia coli', 'Bacteria_3'), ('campylobacter jejuni', 'Bacteria_4')], max_length=256),
        ),
    ]
